# Generated by Django 4.2.1 on 2023-05-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='read',
            field=models.BooleanField(default=True),
        ),
    ]
