# Generated by Django 4.2.1 on 2023-05-29 09:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_msg_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_user',
            name='blacklist',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
