# Generated by Django 4.2.1 on 2023-06-16 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_c_user_groups_alter_c_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.channel'),
            preserve_default=False,
        ),
    ]
